name: End to End Testing

on:
  # https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/
  # pull_request_target is potentially dangerous target so we keep it strict
  # under the label and benefit from secret propagation
  pull_request_target:
    types:
      - synchronize
      - labeled
  workflow_dispatch:

env:
  UP_API_TOKEN: ${{ secrets.UP_API_TOKEN }}
  UP_ORG: ${{ secrets.UP_ORG }}

jobs:
  e2e:
    if: github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'run-e2e-tests')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [go, go-templating, kcl, python]
        test-language: [kcl, python]
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          path: ./template

      - name: Setup Go
        id: setup-go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: '>=1.24.0'
          cache: false

      - name: Install and login with up
        if: env.UP_API_TOKEN != '' && env.UP_ORG != ''
        uses: upbound/action-up@v1
        with:
          api-token: ${{ secrets.UP_API_TOKEN }}
          organization: ${{ secrets.UP_ORG }}
          channel: main

      - name: Initialize project
        run: up project init -e ./template generated-project --language ${{ matrix.language }} --test-language ${{ matrix.test-language }}

      - name: Build project
        run: cd generated-project && up project build

      - name: Switch up context
        if: env.UP_API_TOKEN != '' && env.UP_ORG != ''
        run: up ctx ${{ secrets.UP_ORG }}/upbound-gcp-us-central-1/default

      - name: Run e2e tests
        if: env.UP_API_TOKEN != '' && env.UP_ORG != ''
        run: cd generated-project && up test run tests/* --e2e